mode: deployment

replicaCount: 1

presets:
  # enables the k8sclusterreceiver and adds it to the metrics pipelines
  clusterMetrics:
    enabled: true
  # enables the k8sobjectsreceiver to collect events only and adds it to the logs pipelines
  kubernetesEvents:
    enabled: true

config:
  exporters:
    otlp:
      endpoint: "my-jaeger-collector.default:9411" # the endpoint of Jaeger instance
  service:
    pipelines:
      traces:
        exporters: [otlp]