apiVersion: v1
kind: Pod
metadata:
  name: mxd-performance-test
spec:
  containers:
    - name: mxd-performance-test
      image: hemantxpatel/mxd-performance-test
      args: ["-q", "S"]
  restartPolicy: Never
