apiVersion: v1
kind: Pod
metadata:
  name: mxd-performance-test
spec:
  containers:
    - name: mxd-performance-test
      image: justb4/jmeter:5.5
      command: [ "/bin/sh", "-c", "cd mxd-performance-evaluation && ./mount/run_experiment.sh" ]
      volumeMounts:
      - name: property-volume
        mountPath: /opt/apache-jmeter-5.5/mxd-performance-evaluation/mount

  volumes:
    - name: property-volume
      configMap:
        name: custom-property
        defaultMode: 0500

  restartPolicy: Never
