apiVersion: v1
kind: Pod
metadata:
  name: mxd-performance-test
spec:
  containers:
    - name: mxd-performance-test
      image: ciprian2398/mxd-performance-test:0.2.0-SNAPSHOT
      volumeMounts:
      - name: property-volume
        mountPath: /opt/apache-jmeter-5.5/mxd-performance-evaluation/custom_experiment.properties
        subPath: custom_experiment.properties

  volumes:
    - name: property-volume
      configMap:
        name: custom-property

  restartPolicy: Never
